// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Assets.DreamEngine.Editor.Layers.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class LayersTemplate : LayersTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace ");
            
            #line 21 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public enum ELayer\r\n    {\r\n");
            
            #line 25 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"

	for (int i = 0; i < layerNames.Length; ++i)
	{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 29 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layerNames[i]));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 29 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(layers[i]));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 30 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n    public enum ESortingLayer\r\n    {\r\n");
            
            #line 37 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"

	for (int i = 0; i < sortingLayerNames.Length; ++i)
	{

            
            #line default
            #line hidden
            this.Write("        ");
            
            #line 41 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortingLayerNames[i]));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 41 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sortingLayers[i]));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 42 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write(@"  
    }

    /// <summary>
    /// 层工具
    /// </summary>
	public static class LayerUtility
    {
        public static int GetLayerId(ELayer layer)
        {
            return (int)layer;
        }

        public static int GetSortingLayerId(ESortingLayer layer)
        {
            return (int)layer;
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Projects\InfiniteIsle\InfiniteIsle\Assets\DreamEngine\Editor\Layers\Templates\LayersTemplate.tt"

private string _namespaceNameField;

/// <summary>
/// Access the namespaceName parameter of the template.
/// </summary>
private string namespaceName
{
    get
    {
        return this._namespaceNameField;
    }
}

private string[] _layerNamesField;

/// <summary>
/// Access the layerNames parameter of the template.
/// </summary>
private string[] layerNames
{
    get
    {
        return this._layerNamesField;
    }
}

private string[] _layersField;

/// <summary>
/// Access the layers parameter of the template.
/// </summary>
private string[] layers
{
    get
    {
        return this._layersField;
    }
}

private string[] _sortingLayerNamesField;

/// <summary>
/// Access the sortingLayerNames parameter of the template.
/// </summary>
private string[] sortingLayerNames
{
    get
    {
        return this._sortingLayerNamesField;
    }
}

private string[] _sortingLayersField;

/// <summary>
/// Access the sortingLayers parameter of the template.
/// </summary>
private string[] sortingLayers
{
    get
    {
        return this._sortingLayersField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool namespaceNameValueAcquired = false;
if (this.Session.ContainsKey("namespaceName"))
{
    this._namespaceNameField = ((string)(this.Session["namespaceName"]));
    namespaceNameValueAcquired = true;
}
if ((namespaceNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("namespaceName");
    if ((data != null))
    {
        this._namespaceNameField = ((string)(data));
    }
}
bool layerNamesValueAcquired = false;
if (this.Session.ContainsKey("layerNames"))
{
    this._layerNamesField = ((string[])(this.Session["layerNames"]));
    layerNamesValueAcquired = true;
}
if ((layerNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("layerNames");
    if ((data != null))
    {
        this._layerNamesField = ((string[])(data));
    }
}
bool layersValueAcquired = false;
if (this.Session.ContainsKey("layers"))
{
    this._layersField = ((string[])(this.Session["layers"]));
    layersValueAcquired = true;
}
if ((layersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("layers");
    if ((data != null))
    {
        this._layersField = ((string[])(data));
    }
}
bool sortingLayerNamesValueAcquired = false;
if (this.Session.ContainsKey("sortingLayerNames"))
{
    this._sortingLayerNamesField = ((string[])(this.Session["sortingLayerNames"]));
    sortingLayerNamesValueAcquired = true;
}
if ((sortingLayerNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("sortingLayerNames");
    if ((data != null))
    {
        this._sortingLayerNamesField = ((string[])(data));
    }
}
bool sortingLayersValueAcquired = false;
if (this.Session.ContainsKey("sortingLayers"))
{
    this._sortingLayersField = ((string[])(this.Session["sortingLayers"]));
    sortingLayersValueAcquired = true;
}
if ((sortingLayersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("sortingLayers");
    if ((data != null))
    {
        this._sortingLayersField = ((string[])(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class LayersTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        public System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
